export const EXAM_QUESTIONS = [
  { id: 1, question: "What is Node.js primarily used for?", options: ["Styling web pages", "Running JavaScript on the server", "Database management", "Compiling Java"] },
  { id: 2, question: "Which hook is used for state in React?", options: ["useEffect", "useState", "useMemo", "useRef"] },
  { id: 3, question: "What is JSX?", options: ["Java syntax extension", "JavaScript XML", "JSON XML", "Java execution"] },
  { id: 4, question: "In Next.js, what is used for routing?", options: ["React Router", "Express Router", "File-based routing", "Manual configuration"] },
  { id: 5, question: "What does AWS S3 provide?", options: ["Compute service", "Object storage", "Database", "CDN"] },
  { id: 6, question: "What is Docker?", options: ["Programming language", "Containerization platform", "Database", "Operating system"] },
  { id: 7, question: "Which command builds a Docker image?", options: ["docker start", "docker run", "docker build", "docker init"] },
  { id: 8, question: "What is a Promise in JavaScript?", options: ["A loop", "An async operation handler", "A variable type", "A function call"] },
  { id: 9, question: "What does TypeScript add to JavaScript?", options: ["Styling", "Types", "Backend support", "Database"] },
  { id: 10, question: "What is useEffect used for?", options: ["Styling", "Side effects", "Routing", "State"] },
  { id: 11, question: "What is serverless?", options: ["No servers exist", "Managed backend execution", "Only frontend apps", "Local servers"] },
  { id: 12, question: "What is AWS Lambda?", options: ["Database", "Serverless compute", "CDN", "Storage"] },
  { id: 13, question: "What is WebRTC mainly used for?", options: ["Storage", "Real-time communication", "Styling", "Routing"] },
  { id: 14, question: "What is TRPC?", options: ["REST API", "Type-safe API communication", "Database", "CDN"] },
  { id: 15, question: "What is a monorepo?", options: ["Single file repo", "Multiple repos", "Single repo with multiple projects", "Cloud repo"] },
  { id: 16, question: "What does Turborepo do?", options: ["Styling", "Build system optimization", "Database", "API creation"] },
  { id: 17, question: "What is Kubernetes used for?", options: ["Styling", "Container orchestration", "Database", "Routing"] },
  { id: 18, question: "What is npm?", options: ["Node Package Manager", "Network Protocol Manager", "New Project Maker", "Node Process Manager"] },
  { id: 19, question: "What is SSR in Next.js?", options: ["Static rendering", "Server-side rendering", "Client rendering", "API rendering"] },
  { id: 20, question: "What is JSON?", options: ["Programming language", "Data format", "Database", "Framework"] },
  { id: 21, question: "What happens in Node.js event loop when a Promise resolves?", options: ["Goes to call stack", "Goes to microtask queue", "Goes to callback queue", "Ignored"] },
  { id: 22, question: "Which phase executes setTimeout callbacks?", options: ["Poll", "Timers", "Check", "Close"] },
  { id: 23, question: "In React, what triggers re-render?", options: ["Console log", "State/props change", "CSS change", "DOM access"] },
  { id: 24, question: "What is React Fiber?", options: ["CSS engine", "Rendering engine", "Router", "State manager"] },
  { id: 25, question: "What is hydration in Next.js?", options: ["API fetching", "Attaching JS to SSR HTML", "Styling", "Caching"] },
  { id: 26, question: "What is Incremental Static Regeneration (ISR)?", options: ["Real-time rendering", "Static + dynamic regeneration", "SSR only", "CSR only"] },
  { id: 27, question: "What does edge runtime mean in Next.js?", options: ["Runs on client", "Runs closer to user (CDN edge)", "Runs in database", "Runs in browser"] },
  { id: 28, question: "What is cold start in serverless?", options: ["First request latency", "Server crash", "Network issue", "Cache miss"] },
  { id: 29, question: "What protocol does WebRTC primarily use?", options: ["HTTP", "UDP", "TCP", "FTP"] },
  { id: 30, question: "What is STUN used for in WebRTC?", options: ["Encryption", "NAT traversal", "Streaming", "Storage"] },
  { id: 31, question: "What is TURN server?", options: ["Backup routing server", "Relay server for WebRTC", "CDN", "Database"] },
  { id: 32, question: "In Docker, what is a container?", options: ["VM", "Lightweight isolated environment", "OS", "Image"] },
  { id: 33, question: "Difference between Docker image and container?", options: ["No difference", "Image = blueprint, container = running instance", "Container = blueprint", "Image = runtime"] },
  { id: 34, question: "What is Kubernetes Pod?", options: ["Single container", "Group of containers", "Cluster", "Node"] },
  { id: 35, question: "What is Kubernetes Deployment?", options: ["Storage", "Pod manager", "Load balancer", "Database"] },
  { id: 36, question: "What is Horizontal Pod Autoscaling?", options: ["Scaling vertically", "Scaling pods count", "Scaling CPU only", "Scaling storage"] },
  { id: 37, question: "What does TRPC eliminate?", options: ["Backend", "API layer boilerplate", "Database", "Frontend"] },
  { id: 38, question: "What ensures type safety in TRPC?", options: ["JSON", "TypeScript inference", "REST", "GraphQL"] },
  { id: 39, question: "What is tree shaking?", options: ["Removing unused code", "Sorting files", "Compiling code", "Rendering"] },
  { id: 40, question: "What is code splitting?", options: ["Breaking CSS", "Lazy loading chunks", "Compressing code", "Debugging"] },
  { id: 41, question: "What is memoization in React?", options: ["Storing DOM", "Caching results", "API caching", "State reset"] },
  { id: 42, question: "What is useCallback used for?", options: ["Styling", "Memoizing functions", "API calls", "Routing"] },
  { id: 43, question: "What is closure in JavaScript?", options: ["Function inside loop", "Access to outer scope", "Async function", "Callback"] },
  { id: 44, question: "What is event delegation?", options: ["Multiple listeners", "Parent handles child events", "DOM removal", "Rendering"] },
  { id: 45, question: "What is hoisting?", options: ["Variable movement", "Memory allocation before execution", "Async execution", "Loop behavior"] },
  { id: 46, question: "What is strict mode?", options: ["Faster execution", "Error-prone mode", "Restrictive JS mode", "Debug mode"] },
  { id: 47, question: "What is a monorepo challenge?", options: ["Small size", "Dependency conflicts", "No sharing", "No builds"] },
  { id: 48, question: "What does Turborepo cache?", options: ["API calls", "Build outputs", "Database", "Logs"] },
  { id: 49, question: "What is AWS CloudFront?", options: ["Compute", "CDN", "Database", "Storage"] },
  { id: 50, question: "What is IAM in AWS?", options: ["Storage system", "Access management", "CDN", "Compute"] }
];

export const CORRECT_ANSWERS = {
  1: 1, 2: 1, 3: 1, 4: 2, 5: 1, 6: 1, 7: 2, 8: 1, 9: 1, 10: 1,
  11: 1, 12: 1, 13: 1, 14: 1, 15: 2, 16: 1, 17: 1, 18: 0, 19: 1, 20: 1,
  21: 1, 22: 1, 23: 1, 24: 1, 25: 1, 26: 1, 27: 1, 28: 0, 29: 1, 30: 1,
  31: 1, 32: 1, 33: 1, 34: 1, 35: 1, 36: 1, 37: 1, 38: 1, 39: 0, 40: 1,
  41: 1, 42: 1, 43: 1, 44: 1, 45: 1, 46: 2, 47: 1, 48: 1, 49: 1, 50: 1
};
